# Generated by Django 4.1.6 on 2023-02-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name_of_ar_or_nw',
            new_name='title',
        ),
    ]
